---
- name: Install and configure Apache2
  hosts: localhost
  tasks:
    - name: Update apt-get catalog
      apt:
        update_cache: true
      ignore_errors: True

    - name: Install Apache2 on Ubuntu
      apt:
        name: apache2
        state: latest
      ignore_errors: True

    - name: Start Apache2 servive
      service:
        name: apache2
        state: started
        enabled: yes
